### ISSUE TITLE
Meeting Times

### ISSUE THREAD

**Issue by zteyssier** [zteyssier/JamesBondMCI#1]
I am available from 3:30-6:00 on M, after 3:30 W and F.  I am usually available after 1:30 on T and TH as well.  
I am looking forward to collaborating on this project!  

Thanks!

**Comment by ebeshero** [comment]
@zteyssier I'm available for evening meetings I think on MW and often F, and usually T H afternoons / evenings are good. I can meet on Saturdays too. I'll be trying to make the rounds of all the teams to help get everyone off to a strong start, and come in strategically at various moments when you need me, though I may not be able to come to every meeting. I'll try to come to as many meetings as I can, but you all arrange these on your schedule. 

It's good to meet and **talk** with your group every week to make sure everyone is on the same page, put out any fires, and make a clear plan where everyone can see it and stick with it. So we'll talk about this stuff more tomorrow in class!

**Comment by CTrohoske01** [comment]
I'm available from 11:00-2:30 & 4:30-10:00 MWF and anything after 4:30 TTh! I can start going around and collecting the soundtracks from each movie (26 total, correct?) to see what we're dealing with.

**Comment by zteyssier** [comment]
@CTrohoske01 Chase, that is a good thought, however, that is too much work for one person at this stage.  I was thinking we can split the work evenly.  We will discuss this more during the first meeting.  If you have any other questions feel free to ask.  I also posted a new issue as well.

**Comment by zteyssier** [comment]
@dpakulski42 Can you let us know when you are available so we can have a meeting next week? Thanks!

**Comment by dpakulski42** [comment]
I'm available after 1:30 on MWF and before 3:00 on TTh.

**Comment by zteyssier** [comment]
@ebeshero @CTrohoske01 @dpakulski42 

Let’s have our first meeting on M at 5.  I made a mistake saying 3:30-6 for M.  That time frame is for W instead.  In the meantime start thinking about which films and intro songs you would like to focus on.  I was thinking one of us could do the first 9 films/songs, and so on. (Since 27 divides evenly.) 

We can finalize the workload at the meeting.  Let me know if you have any questions.

Enjoy your weekend!

**Comment by dpakulski42** [comment]
@CTrohoske01 @zteyssier 

Hey team!

Sorry I missed the meeting yesterday. I've been out of town in Rochester these last couple of weekends to shoot a film so I haven't had time to focus on much else. I just caught myself up by watching the recording of the meeting. I was hoping to get to watch the classics so I'm pumped to do the first nine films.

Can we set up a meeting sometime this week? Tomorrow afternoon would work great for me or Friday if you guys can't.

**Comment by zteyssier** [comment]
@dpakulski42 @CTrohoske01 

Hey everyone,

I think we could have a meeting at 5 on Friday since the second project checkpoint is due Monday and requires a lot of progress.  Before then, let’s try to have one film from each of our sets marked up on XML.  If we can get one of our  songs marked up, this would also help for the meeting. 

 As always let me know if you have any questions.  

Thanks!

**Comment by dpakulski42** [comment]
@CTrohoske01 @zteyssier 

5 sounds good. 

Have we determined consistent terms to use in our markup yet? And are we doing entire scripts or just the songs?

**Comment by zteyssier** [comment]
@CTrohoske01 @dpakulski42 

This is an issue.  I think we can use camel case for elements with more than 1 name, and capitalize the first letter for single name elements.  (Ex:  JamesBond, James).  I think it might make more sense to try to have at least one song marked up, since we can easily edit each once we establish the RNG schema tomorrow.  If we can each do one script for tomorrow, it would help, but if not don’t worry about it.  

We also have to figure out if we are doing a standard schema for the screenplays and songs, or if we are doing a separate schema for the screenplays and a separate one for the songs.  

Thanks!

**Comment by CTrohoske01** [comment]
@dpakulski42 @zteyssier 
I don't know if I'll be able to make it to the meeting tomorrow since I'll be traveling, but I will definitely watch the recording as soon as I get the chance. Camel case works for me! So far I've gotten all the available scripts of mine and turned them into txt files. I will start marking up one and definitely get an into song marked up. I think it would be a good idea to do two separate schemas for the screenplays and songs. If you guys would like we could have a meeting late Sunday night, say around 10 PM, to share what we have done and organize everything for Monday. Let me know if that works for you guys!

**Comment by zteyssier** [comment]
@dpakulski42 @CTrohoske01 

I updated the notepad file yesterday, with some minor edits to the intro songs.  

Thanks!

**Comment by ebeshero** [comment]
@zteyssier @dpakulski42 @CTrohoske01 Sorry I missed yesterday’s meeting—but if you can push some files to the repo I can comment and send back some suggestions for the markup and schema...

**Comment by zteyssier** [comment]
@ebeshero @dpakulski42 @CTrohoske01 

I think it would make sense to have one more meeting before Monday.  Chase can you meet around 9 instead, if not we could do a short meeting at 10. 

Thanks!

**Comment by CTrohoske01** [comment]
Unfortunately I won't be able to meet later tonight, got caught up with some stuff, really sorry! I finished up my markup for the theme songs so I'll push everything up to the repo. I think we have plenty of enough for the checkpoint for tomorrow. If you have any questions feel free to post them here and I'll be able to respond.

**Comment by zteyssier** [comment]
@ebeshero @dpakulski42 @CTrohoske01 

After some more thought I realized if we can push all of our files to the repo before class, there is no need for a meeting tonight.  

In the meantime I will provide a few materials for everyone to consider when analyzing the film sets.

On Her Majesty’s Secret Service:  

![88518001-6D62-4272-A5C6-B3D06CB2C7AB](https://user-images.githubusercontent.com/70618741/95028386-ee0d8f00-066d-11eb-9e67-27688f27ec96.jpeg)

This documentary may help with George Lazenby’s portrayal of Bond.  This would probably be more geared towards the first set, but feel free to check it out.

The history of 007:

![83EFF872-C36C-41FB-9C59-1D06E3E5B536](https://user-images.githubusercontent.com/70618741/95028493-86a40f00-066e-11eb-925d-b925fe4d07c9.jpeg)

This one will probably help all of us out.  This could be used as a precursor to the films to help us further analyze 007.  Feel free to check it out if you get a chance.

Thanks everyone!
